language: node_js
node_js:
  - "0.12"
  - "4"
  - "5"
  - "iojs"
before_install:
  - "npm install -g npm"
  - "npm --version"
  - "npm install -g mocha"
  - "npm install -g typescript"
  - "npm install -g tsd"
  - "ls"
#  - "tsd reinstall --save"
#  - "npm run-script build"
  - "npm install"
script:
  - "npm run test"