language: node_js
node_js:
  - "0.12"
  - "4"
  - "5"
  - "iojs"
before_install:
  - "npm install -g mocha"
  - "npm install -g typescript"
  - "npm install -g tsd"
#  - "tsd reinstall --save"
#  - "npm run-script build"
  - "npm install --ignore-scripts"
install: off
script:
  - "npm run test"