language: node_js
node_js:
  - "0.12"
  - "4"
  - "5"
  - "iojs"
script: "npm run test"
before_install:
  - "npm install -g mocha"
  - "npm install -g typescript"
  - "npm install -g tsd"
  - "npm install"
  - "tsd reinstall --save"
  - "npm run build"