environment:
  matrix:
    - nodejs_version: "0.12"
    - nodejs_version: "1.8"
    - nodejs_version: "2.5"
    - nodejs_version: "3.3"
    - nodejs_version: "4.2"
    - nodejs_version: "5.5"
install:
  - "npm install typescript"
  - "npm install"
  - "npm run build"
build: on
test_script:
  - "npm run test"
version: "{build}"